AllCops:
  Exclude:
    - db/**/*
    - bundle_bin/**/*
    - spec/**/*
  Include:
    - exe/crossmap
    - "**/Gemfile"
    - "**/Rakefile"
Layout/DotPosition:
  EnforcedStyle: trailing
Style/StringLiterals:
  EnforcedStyle: double_quotes
