AllCops:
  Exclude:
    - db/**/*
    - bundle_bin/**/*
    - spec/**/*
  Include:
    - exe/crossmap
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/DotPosition:
  EnforcedStyle: trailing
