#!/usr/bin/env ruby
require "optparse"
require "gn_crossmap"

puts "This program requires Ruby >= v. 2.1.0" if RUBY_VERSION < "2.1.0"

CATALOGUE_OF_LIFE = 1
OUTPUT = "output.csv"
OPTIONS = {
  data_source_id: CATALOGUE_OF_LIFE,
  output: OUTPUT
}

options = {}

OptionParser.new do |opts|
  script_name = File.basename($PROGRAM_NAME)
  opts.banner = "Usage: #{script_name} [options]"

  opts.on("-d", "--data_source_id", String,
          "Data Source Id according to GN Resolver",
          "Default: #{CATALOGUE_OF_LIFE}") { |d| options[:id] = d }

  opts.on("-i", "--input", String, "Path to input CSV file") do |inp|
    options[:input] = inp
  end

  opts.on("-o", "--output", String,
          "Path to output CSV file",
          "Default: #{OUTPUT}") { |out| options[:output] = out }

  opts.separator ""

  opts.on("-h", "--help", "Show this help message.") do
    puts opts
    exit
  end

end.parse!
require "byebug"; byebug
OPTIONS[:input] = File.expand_path(options[:input])
OPTIONS[:output] = File.expand_path(options[:output]) if options[:output]
OPTIONS[:data_source_id] = options[:id] if options[:id]
GnCrossmap.run(OPTIONS[:input], OPTIONS[:output], OPTIONS[:data_source_id])
