#!/usr/bin/env ruby
# frozen_string_literal: true

require "trollop"
require "gn_crossmap"

puts "This program requires Ruby >= v. 2.4.1" if RUBY_VERSION < "2.4.1"

CATALOGUE_OF_LIFE = 1
OUTPUT = "output.csv"
opts = Trollop.options do
  banner "Compares a list of scientific names to scientific names from a " \
    "data source from Global Names Resolver\n\n " \
    "Usage:\n  crossmap [options]\n\noptions:" \
    "\n\n  ('-i -' reads from STDIN; '-o -' writes to STDOUT)\n\n"

  opt(:input, "Path to input file", type: :string)
  opt(:output, "Path to output file", default: OUTPUT)
  opt(:data_source_id, "Data source id from GN Resolver",
      default: CATALOGUE_OF_LIFE)
  opt(:skip_original, "If given, only 'taxonID' is shown " \
      "from the original input", type: :boolean)
  opt(:with_classification, "If given, returns classification path of " \
                            "matched names", type: :boolean)
end

Trollop.die :input, "must be set" if opts[:input].nil?
unless File.exist?(opts[:input]) || opts[:input] == "-"
  Trollop.die :input, "file must exist"
end

begin
  GnCrossmap.run(opts)
rescue GnCrossmapError => e
  GnCrossmap.logger.error(e.message)
end
