#!/usr/bin/env ruby
require "trollop"
require "gn_crossmap"

puts "This program requires Ruby >= v. 2.1.0" if RUBY_VERSION < "2.1.0"

CATALOGUE_OF_LIFE = 1
OUTPUT = "output.csv"
opts = Trollop.options do
  banner "Compares a list of scientific names to scientific names from a " \
    "data source from Global Names Resolver\n\n " \
    "Usage:\n  crossmap [options]\n\noptions:"

  opt(:input, "Path to intput file", type: :string)
  opt(:output, "Path to output file", default: OUTPUT)
  opt(:data_source_id, "Data source id from GN Resolver",
      default: CATALOGUE_OF_LIFE)
end

Trollop.die :input, "must be set" if opts[:input].nil?
Trollop.die :input, "file must exist" unless File.exist?(opts[:input])

begin
  GnCrossmap.run(opts[:input], opts[:output], opts[:data_source_id])
rescue GnCrossmapError => e
  GnCrossmap.logger.error(e.message)
end
